services:
  - type: web
    name: chatbot-backend
    env: python
    buildCommand: ""  # No build needed for plain Python
    startCommand: python3 app.py
    rootDir: backend

  - type: static
    name: chatbot-frontend
    buildCommand: npm install && npm run build
    staticPublishPath: build
    rootDir: research-chatbot
